minimum_pre_commit_version: 1.0.0
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
      - id: mypy
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
