minimum_pre_commit_version: 1.0.0
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
      - id: debug-statements
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    sha: master
    hooks:
      - id: mypy
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/prettier/prettier
    sha: master
    hooks:
      - id: prettier
